### ISSUE TITLE
New mirror in Singapore?

### ISSUE THREAD

**Issue by karibuTW** [MX-Linux/mx-repo-list#15]
Hello,
I'm the admin of the MXLinux https://mirror.freedif.org/ and I am not receiving much traffic with the ISOs.
It seems I am listed under Vietnam, but in fact the mirror is based in Singapore. May be this should be fixed.

Also, will a new mirror for the repo be helpful? I have spare bandwidth and space.

Thanks

**Comment by AdrianTM** [comment]
I see it's listed under Singapore #Singapore - https://mirror.freedif.org/MXLinux/repo
but it was commented out 4 months ago. We usually remove repos that we are having connectivity problems with or if they are not up to date.

I will fix the location in this list which I see it indeed under Vietnam https://rsync-mxlinux.org/mirmon/

I don't think we need another ISO mirror if the current one is not getting much traffic.

**Comment by karibuTW** [comment]
>
>
> Well noted,> The connectivity issued have been fixed, hope you can add it again.
>
>
>
Thank you
>
>
> Kari> --> Sent with Tutanota
>
>
> 1 Feb 2023, 21:48 by ***@***.***:
>
> I see it's listed under Singapore #Singapore - https://mirror.freedif.org/MXLinux/repo> but it was commented out 4 months ago. We usually remove repos that we are having connectivity problems with or if they are not up to date.
> I will fix the location in this list which I see it indeed under Vietnam https://rsync-mxlinux.org/mirmon/
> I don't think we need another ISO mirror if the current one is not getting much traffic.
> —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you authored the thread.￼
>
>
>
>

**Comment by karibuTW** [comment]
I've done like this:
https://mxlinux.org/wiki/rsyncserver/mirroring-mx-antix-linux/

But I guess this is only for Antix.
What depo I need to rsync then?

Thank you

**Comment by AdrianTM** [comment]
It should work for MX too, but one thing the person who is taking care of that told me:

> I just discovered that if you haven't already at least started to sync, having the --delete after the -rtv throws an error. If any thing has been downloaded already it doesn't so existing mirrors wouldn't have seen it.
--del before the -rtv does not.

**Comment by karibuTW** [comment]
okay got it, i've done the needed change and it is running fine now, but not sure I got it all

I use this:

```
DESTPATH="/media/Stockage/Mirrors/MXLinux/repo"
RSYNC=/usr/bin/rsync
export RSYNC_PASSWORD=T1tpw4rstmr
LOCKFILE=/tmp/rsync-mxlinux-package.lock

$RSYNC --delete-delay -rtv --timeout=3600 --contimeout=3600 rsuser@iso.mxrepo.com::workspace "$DESTPATH"
```

Is this okay?

Thank you

**Comment by AdrianTM** [comment]
Looks OK, I however still don't see the "mx" on your server, I see only the "antix" one.

**Comment by karibuTW** [comment]
I got the MX in ISO now: https://mirror.freedif.org/MXLinux/isos/
Not in the repo tho. Yet it says fully synced.

**Comment by AdrianTM** [comment]
I don't see the repo there either. I see only the MX ISOs.

**Comment by karibuTW** [comment]
Okay, it is now fixed:
https://mirror.freedif.org/MXLinux/repo/

Thank you

**Comment by AdrianTM** [comment]
Thanks, I re-enabled the repo [73f807c](https://github.com/MX-Linux/mx-repo-list/commit/73f807c459ac8eb262504a068f39b4a7a78de4ad)
