### ISSUE TITLE
Anycast - no flag icon

### ISSUE THREAD

**Issue by anticapitalista** [MX-Linux/mx-repo-list#2]
Anycast - no flag icon

**Comment by AdrianTM** [comment]
Yep, I don't have a world or UN flag in fskbsetting that I use as a flag source, any suggestions?

**Comment by anticapitalista** [comment]
Since it is an antiX built app, I can add a globe image. What shall be name it as to make it easy for repo-manager to pick it up?

**Comment by AdrianTM** [comment]
It won't be picked up automatically, it depends what name we use for "country", I would use "world" or "any" or "UN" if you use UN flag. Then I will adjust the code to display that flag, just let me know.

**Comment by anticapitalista** [comment]
Do we want it to appear as the first name in the list? If so any seems ok

**Comment by AdrianTM** [comment]
Right now I have "Anycast, Worldwide" In any case, no matter what the name of the file would be I will need to add something like  "if (country == "Anycast") display X.png"

**Comment by anticapitalista** [comment]
I'll call it any.png

**Comment by anticapitalista** [comment]
Built and sent to upload
